FROM debian:bookworm

WORKDIR /build

ARG CPU_ARCH

RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    python3 \
    python3-pip \
    python3-venv \
    git

RUN python3 -m venv venv

RUN venv/bin/pip install -U pip && \
    venv/bin/pip install fpm

COPY fpm.toml ./
COPY app ./app
COPY src ./src
COPY scripts ./scripts

RUN chmod +x ./scripts/build_executables.sh

ENV CPU_ARCH=${CPU_ARCH}

CMD ["/bin/bash", "-c", "./scripts/build_executables.sh ${CPU_ARCH}"]
