FROM debian:bookworm

ARG CPU_ARCH

WORKDIR /build

RUN apt-get update && apt-get install -y \
    build-essential \
    gfortran \
    python3 \
    python3-pip \
    python3-venv \
    git

RUN python3 -m venv venv

RUN venv/bin/pip install -U pip && \
    venv/bin/pip install fpm

COPY fpm.toml ./
COPY app ./app
COPY src ./src
COPY scripts ./scripts

RUN chmod +x ./scripts/build_executables.sh

CMD ["./scripts/build_executables.sh", "${CPU_ARCH}"]
